version: "3"
services:
  web:
    build: .
    env_file:
      - .env.docker
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - postgresql
      - redis
    restart: on-failure
  celery_worker:
    build: .
    env_file:
      - .env.docker
    volumes:
      - .:/app
    depends_on:
      - postgresql
      - redis
    command: celery -A api_demo worker -l INFO
    restart: on-failure
  redis:
    image: redis:alpine
    ports:
      - "63790:6379"
    restart: always
  postgresql:
    image: postgres:alpine
    env_file:
      - .env.postgresql
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    restart: always